CREATE DATABASE IF NOT EXISTS nursing_home
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE nursing_home;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS notice;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS nursing_record;
DROP TABLE IF EXISTS health_record;
DROP TABLE IF EXISTS bed;
DROP TABLE IF EXISTS room_bed;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS staff_info;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS elderly;
DROP TABLE IF EXISTS sys_user;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
  password VARCHAR(100) NOT NULL COMMENT '密码',
  real_name VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
  role VARCHAR(20) NOT NULL DEFAULT 'admin' COMMENT '角色',
  phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='系统用户表';

CREATE TABLE elderly (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  name VARCHAR(50) NOT NULL COMMENT '姓名',
  gender VARCHAR(10) DEFAULT NULL COMMENT '性别',
  age INT DEFAULT NULL COMMENT '年龄',
  id_card VARCHAR(30) DEFAULT NULL COMMENT '身份证号',
  phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  family_phone VARCHAR(20) DEFAULT NULL COMMENT '家属电话',
  address VARCHAR(255) DEFAULT NULL COMMENT '家庭住址',
  check_in_date DATE DEFAULT NULL COMMENT '入住日期',
  status VARCHAR(20) NOT NULL DEFAULT '在住' COMMENT '状态',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='老人信息表';

CREATE TABLE staff (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  name VARCHAR(50) NOT NULL COMMENT '姓名',
  gender VARCHAR(10) DEFAULT NULL COMMENT '性别',
  age INT DEFAULT NULL COMMENT '年龄',
  phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  position VARCHAR(50) DEFAULT NULL COMMENT '职位',
  entry_date DATE DEFAULT NULL COMMENT '入职日期',
  status VARCHAR(20) NOT NULL DEFAULT '在职' COMMENT '状态',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='员工信息表';

CREATE TABLE staff_info (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '员工ID',
  name VARCHAR(50) NOT NULL COMMENT '员工姓名',
  gender VARCHAR(10) DEFAULT NULL COMMENT '性别',
  age INT DEFAULT NULL COMMENT '年龄',
  phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  position VARCHAR(50) DEFAULT NULL COMMENT '岗位',
  department VARCHAR(50) DEFAULT NULL COMMENT '部门',
  hire_date DATE DEFAULT NULL COMMENT '入职日期',
  status VARCHAR(20) NOT NULL DEFAULT '在职' COMMENT '状态',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='员工信息表';

CREATE TABLE room (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  room_no VARCHAR(30) NOT NULL UNIQUE COMMENT '房间号',
  floor INT DEFAULT NULL COMMENT '楼层',
  room_type VARCHAR(30) DEFAULT NULL COMMENT '房间类型',
  bed_count INT NOT NULL DEFAULT 0 COMMENT '床位数量',
  status VARCHAR(20) NOT NULL DEFAULT '正常' COMMENT '状态',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='房间表';

CREATE TABLE bed (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  room_id BIGINT NOT NULL COMMENT '房间ID',
  bed_no VARCHAR(30) NOT NULL COMMENT '床位编号',
  elderly_id BIGINT DEFAULT NULL COMMENT '老人ID',
  status VARCHAR(20) NOT NULL DEFAULT '空闲' COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_bed_room FOREIGN KEY (room_id) REFERENCES room(id),
  CONSTRAINT fk_bed_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id)
) COMMENT='床位表';

CREATE TABLE room_bed (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  building_no VARCHAR(30) DEFAULT NULL COMMENT '楼栋号',
  room_no VARCHAR(30) NOT NULL COMMENT '房间号',
  bed_no VARCHAR(30) NOT NULL COMMENT '床位号',
  bed_type VARCHAR(30) DEFAULT NULL COMMENT '床位类型',
  status VARCHAR(20) NOT NULL DEFAULT '空闲' COMMENT '床位状态',
  elderly_id BIGINT DEFAULT NULL COMMENT '入住老人ID',
  elderly_name VARCHAR(50) DEFAULT NULL COMMENT '入住老人姓名',
  price DECIMAL(10,2) DEFAULT NULL COMMENT '床位费用',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='房间床位表';

CREATE TABLE health_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  elderly_id BIGINT NOT NULL COMMENT '老人ID',
  elderly_name VARCHAR(50) NOT NULL COMMENT '老人姓名',
  gender VARCHAR(10) DEFAULT NULL COMMENT '性别',
  age INT DEFAULT NULL COMMENT '年龄',
  blood_pressure VARCHAR(30) DEFAULT NULL COMMENT '血压',
  blood_sugar VARCHAR(30) DEFAULT NULL COMMENT '血糖',
  heart_rate INT DEFAULT NULL COMMENT '心率',
  weight DECIMAL(5,2) DEFAULT NULL COMMENT '体重',
  medical_history VARCHAR(500) DEFAULT NULL COMMENT '既往病史',
  allergy_history VARCHAR(500) DEFAULT NULL COMMENT '过敏史',
  medication VARCHAR(500) DEFAULT NULL COMMENT '用药情况',
  health_status VARCHAR(30) NOT NULL DEFAULT '良好' COMMENT '健康状态',
  check_date DATE DEFAULT NULL COMMENT '检查日期',
  doctor_name VARCHAR(50) DEFAULT NULL COMMENT '检查医生',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_health_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id)
) COMMENT='健康档案表';

CREATE TABLE nursing_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  elderly_id BIGINT NOT NULL COMMENT '老人ID',
  staff_id BIGINT NOT NULL COMMENT '员工ID',
  care_type VARCHAR(50) DEFAULT NULL COMMENT '护理类型',
  care_content VARCHAR(1000) DEFAULT NULL COMMENT '护理内容',
  care_time DATETIME DEFAULT NULL COMMENT '护理时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_nursing_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id),
  CONSTRAINT fk_nursing_staff FOREIGN KEY (staff_id) REFERENCES staff(id)
) COMMENT='护理记录表';

CREATE TABLE payment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  elderly_id BIGINT NOT NULL COMMENT '老人ID',
  amount DECIMAL(10,2) NOT NULL COMMENT '缴费金额',
  payment_type VARCHAR(30) DEFAULT NULL COMMENT '缴费类型',
  payment_date DATE DEFAULT NULL COMMENT '缴费日期',
  status VARCHAR(20) NOT NULL DEFAULT '已缴费' COMMENT '状态',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_payment_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id)
) COMMENT='缴费记录表';

CREATE TABLE notice (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  title VARCHAR(100) NOT NULL COMMENT '公告标题',
  content TEXT COMMENT '公告内容',
  publisher VARCHAR(50) DEFAULT NULL COMMENT '发布人',
  publish_time DATETIME DEFAULT NULL COMMENT '发布时间',
  status VARCHAR(20) NOT NULL DEFAULT '显示' COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='公告表';

INSERT INTO sys_user (username, password, real_name, role, phone, status)
VALUES ('admin', '123456', '系统管理员', 'admin', '13800000000', 1);
