CREATE DATABASE IF NOT EXISTS nursing_home
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE nursing_home;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS notice;
DROP TABLE IF EXISTS payment_record;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS nursing_record;
DROP TABLE IF EXISTS health_record;
DROP TABLE IF EXISTS bed;
DROP TABLE IF EXISTS room_bed;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS staff_info;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS elderly;
DROP TABLE IF EXISTS sys_user;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  real_name VARCHAR(50) DEFAULT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'admin',
  phone VARCHAR(20) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='系统用户表';

CREATE TABLE elderly (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  gender VARCHAR(10) DEFAULT NULL,
  age INT DEFAULT NULL,
  id_card VARCHAR(30) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  family_phone VARCHAR(20) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  check_in_date DATE DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '在住',
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='老人信息表';

CREATE TABLE staff (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  gender VARCHAR(10) DEFAULT NULL,
  age INT DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  position VARCHAR(50) DEFAULT NULL,
  entry_date DATE DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '在职',
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='员工信息表';

CREATE TABLE staff_info (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  gender VARCHAR(10) DEFAULT NULL,
  age INT DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  position VARCHAR(50) DEFAULT NULL,
  department VARCHAR(50) DEFAULT NULL,
  hire_date DATE DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '在职',
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='员工信息表';

CREATE TABLE room (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  room_no VARCHAR(30) NOT NULL UNIQUE,
  floor INT DEFAULT NULL,
  room_type VARCHAR(30) DEFAULT NULL,
  bed_count INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT '正常',
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='房间表';

CREATE TABLE bed (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  room_id BIGINT NOT NULL,
  bed_no VARCHAR(30) NOT NULL,
  elderly_id BIGINT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '空闲',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bed_room FOREIGN KEY (room_id) REFERENCES room(id),
  CONSTRAINT fk_bed_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id)
) COMMENT='床位表';

CREATE TABLE room_bed (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  building_no VARCHAR(30) DEFAULT NULL,
  room_no VARCHAR(30) NOT NULL,
  bed_no VARCHAR(30) NOT NULL,
  bed_type VARCHAR(30) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '空闲',
  elderly_id BIGINT DEFAULT NULL,
  elderly_name VARCHAR(50) DEFAULT NULL,
  price DECIMAL(10,2) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='房间床位表';

CREATE TABLE health_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  elderly_id BIGINT NOT NULL,
  elderly_name VARCHAR(50) NOT NULL,
  gender VARCHAR(10) DEFAULT NULL,
  age INT DEFAULT NULL,
  blood_pressure VARCHAR(30) DEFAULT NULL,
  blood_sugar VARCHAR(30) DEFAULT NULL,
  heart_rate INT DEFAULT NULL,
  weight DECIMAL(5,2) DEFAULT NULL,
  medical_history VARCHAR(500) DEFAULT NULL,
  allergy_history VARCHAR(500) DEFAULT NULL,
  medication VARCHAR(500) DEFAULT NULL,
  health_status VARCHAR(30) NOT NULL DEFAULT '良好',
  check_date DATE DEFAULT NULL,
  doctor_name VARCHAR(50) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_health_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id)
) COMMENT='健康档案表';

CREATE TABLE nursing_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  elderly_id BIGINT NOT NULL,
  elderly_name VARCHAR(50) NOT NULL,
  staff_id BIGINT NOT NULL,
  staff_name VARCHAR(50) NOT NULL,
  nursing_type VARCHAR(50) DEFAULT NULL,
  nursing_content VARCHAR(1000) DEFAULT NULL,
  nursing_result VARCHAR(1000) DEFAULT NULL,
  nursing_date DATE DEFAULT NULL,
  nursing_time TIME DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '正常',
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_nursing_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id),
  CONSTRAINT fk_nursing_staff_info FOREIGN KEY (staff_id) REFERENCES staff_info(id)
) COMMENT='护理记录表';

CREATE TABLE payment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  elderly_id BIGINT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  payment_type VARCHAR(30) DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT '已缴费',
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id)
) COMMENT='缴费记录表';

CREATE TABLE payment_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  elderly_id BIGINT NOT NULL,
  elderly_name VARCHAR(50) NOT NULL,
  fee_type VARCHAR(30) DEFAULT NULL,
  amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  payment_status VARCHAR(20) NOT NULL DEFAULT '未缴费',
  payment_method VARCHAR(20) DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  billing_month VARCHAR(20) DEFAULT NULL,
  operator_name VARCHAR(50) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_record_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id)
) COMMENT='缴费记录表';

CREATE TABLE notice (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  content TEXT,
  notice_type VARCHAR(30) DEFAULT NULL,
  publish_status VARCHAR(20) NOT NULL DEFAULT '草稿',
  publisher VARCHAR(50) DEFAULT NULL,
  publish_time DATETIME DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='公告表';

INSERT INTO sys_user (username, password, real_name, role, phone, status)
VALUES ('admin', '123456', '系统管理员', 'admin', '13800000000', 1);
